[supervisord]
nodaemon=true
user=root
logfile=/home/firefox/supervisord.log
pidfile=/home/firefox/supervisord.pid


[program:xvfb]
user=root
command=/bin/bash -c "rm -rf /tmp/.X0-lock /tmp/.X11-unix/X0 && mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix && Xvfb :0 -screen 0 1920x1080x24 -ac"
environment=DISPLAY=":0"
autorestart=true
priority=10

	
[program:openbox]
user=firefox
command=openbox-session
environment=DISPLAY=":0",HOME="/home/firefox"
autorestart=true
priority=20


[program:vnc]
user=root
command=/bin/bash -c "sleep 3 && x11vnc -display :0 -forever -shared -rfbport 5900 -nopw"
environment=DISPLAY=:0
autorestart=true
priority=30


[program:novnc]
user=firefox
command=websockify --web=/usr/share/novnc/ 3000 localhost:5900
autorestart=true
priority=40


[program:firefox]
user=firefox
command=/bin/bash -c "until xdpyinfo -display :0 >/dev/null 2>&1; do sleep 1; done; firefox --no-remote --profile /config/profile/default"
environment=DISPLAY=":0",HOME="/home/firefox"
autorestart=true
priority=50
